SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [immflydb].[LOCATION](
	[ID] [uniqueidentifier] NOT NULL,
	[CITY] [varchar](50) NOT NULL,
	[ALTERNATE_IDENT] [uniqueidentifier] NOT NULL,
	[AIRPORT_NAME] [varchar](100) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [immflydb].[LOCATION] ADD  CONSTRAINT [PK_LOCATION_ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO