SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [immflydb].[FLIGHT](
	[ID] [uniqueidentifier] NOT NULL,
	[FA_FLIGHT_ID] [uniqueidentifier] NOT NULL,
	[AIRLINE] [varchar](50) NOT NULL,
	[AIRLINE_IATA] [varchar](50) NOT NULL,
	[FLIGHT_NUMBER] [uniqueidentifier] NOT NULL,
	[TAIL_NUMBER] [uniqueidentifier] NOT NULL,
	[TYPE] [varchar](50) NOT NULL,
	[CODESHARES] [varchar](50) NOT NULL,
	[BLOCKED] [bigint] NOT NULL,
	[DIVERTED] [bigint] NOT NULL,
	[CANCELLED] [bigint] NOT NULL,
	[ORIGIN_ID] [uniqueidentifier] NOT NULL,
	[DESTINATION_ID] [uniqueidentifier] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [immflydb].[FLIGHT] ADD  CONSTRAINT [PK_FLIGHT_ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [immflydb].[FLIGHT]  WITH CHECK ADD  CONSTRAINT [FK_FLIGHT_DESTINATION_ID] FOREIGN KEY([DESTINATION_ID])
REFERENCES [immflydb].[LOCATION] ([ID])
GO
ALTER TABLE [immflydb].[FLIGHT] CHECK CONSTRAINT [FK_FLIGHT_DESTINATION_ID]
GO
ALTER TABLE [immflydb].[FLIGHT]  WITH CHECK ADD  CONSTRAINT [FK_FLIGHT_LOCATION_ID] FOREIGN KEY([ORIGIN_ID])
REFERENCES [immflydb].[LOCATION] ([ID])
GO
ALTER TABLE [immflydb].[FLIGHT] CHECK CONSTRAINT [FK_FLIGHT_LOCATION_ID]
GO